version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: vita_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/vita_db

volumes:
  postgres_data:
